name: push

on:
  push:
  schedule:
    - cron: '0 8 * * 1'  # Mondays at 8am

jobs:

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install -q black
    - run: black --check .
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.x' ]
    name: test-v${{matrix.python-version}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - run: pip install -q -U pip -r requirements-test.txt
    - run: >-
        python -m pytest
        --durations=10
        --cov=./
        --cov-append
        --cov-report=term-missing
        --cov-report=xml

  coverage:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
